version: '3'

services:
  wicardd:
    build: .
    ports:
      - "8888:8888"
      - "9000:9000"
      - "50000:50000"
    cap_add:
      - NET_ADMIN
    restart: always
    environment:
      - RUN_OPTS=wicardd-x64.1.19 # Default version...
